trigger:
- main

pool:
  name: 'aws'
  
variables:
  AWS_REGION: 'eu-west-1'
  AWS_ACCESS_KEY_ID: $(AKIA47CRYSQF4GAAUDVD)
  AWS_SECRET_ACCESS_KEY: $(secret_key)


stages:
- stage: InstallTerraform
  displayName: 'Install Terraform'
  jobs:
  - job: InstallTerraform
    displayName: 'Install Terraform'
    pool:
      name: 'aws'

    steps:
    - script: |
        # Install unzip utility
        sudo apt-get update
        sudo apt-get install -y unzip

        # Download Terraform binary
        curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o terraform.zip
        
        # Unzip Terraform binary
        unzip terraform.zip

        # Move Terraform binary to /usr/local/bin directory (you might need sudo privileges)
        sudo mv terraform /usr/local/bin/terraform

        # Verify Terraform installation
        terraform --version
      displayName: 'Install Terraform'

- stage: Deploy
  jobs:
  - job: TerraformInit
    displayName: 'Terraform Init and Apply'
    steps: 
    - script: |
        cd $(System.DefaultWorkingDirectory)/infra
        terraform --version
      displayName: 'Check Terraform version'

    - script: |
        terraform init
      displayName: 'Terraform Init'
    
    - script: |
        terraform apply -auto-approve
      displayName: 'Terraform Apply'

    - script: |
        echo '[all]' > hosts
        terraform output -json instance_ips | jq -r '.[]' | awk '{print $1 " ansible_user=ec2-user"}' >> hosts
      displayName: 'Generate Ansible hosts file'
      
- stage: Configure
  dependsOn: Deploy
  jobs:
  - job: Ansible
    displayName: 'Run Ansible Playbook'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt-get install -y ansible
        ansible --version
      displayName: 'Install Ansible'

    - script: |
        ansible-playbook -i hosts playbook.yml
      displayName: 'Run Ansible Playbook'