---
- name: Distribute the instance IPs file to target machines
  hosts: all
  tasks:
    - name: Copy the instance IPs file to the target machine
      copy:
        src: /tmp/instance_ips.txt
        dest: /tmp/instance_ips.txt

    - name: Display the contents of the instance IPs file
      command: cat /tmp/instance_ips.txt
      register: ip_file_content

    - name: Show the instance IPs file content
      debug:
        msg: "Contents of instance_ips.txt on {{ inventory_hostname }}: {{ ip_file_content.stdout }}"
        
- name: Run script on deployed machines
  hosts: all
  tasks:
    - name: Display the hostname of the current server
      debug:
        msg: "Connected to server: {{ inventory_hostname }}"

    - name: Ensure ping script has execute permission
      file:
        path: /tmp/ping_script.sh
        mode: '0755'
        state: file

    - name: Check if ping script exists
      stat:
        path: /tmp/ping_script.sh
      register: ping_script

    - name: Fail if ping script does not exist
      fail:
        msg: "/tmp/ping_script.sh does not exist on {{ inventory_hostname }}"
      when: not ping_script.stat.exists

    - name: Display the contents of the ping script
      shell: cat /tmp/ping_script.sh
      register: script_content
      ignore_errors: yes

    - name: Print the contents of the ping script
      debug:
        msg: "Contents of /tmp/ping_script.sh on {{ inventory_hostname }}: {{ script_content.stdout }}"

    - name: Run ping script
      shell: /tmp/ping_script.sh
      register: result
      ignore_errors: yes

    - name: Print result of running the script
      debug:
        msg: "Result of running the script on {{ inventory_hostname }}: stdout={{ result.stdout }} stderr={{ result.stderr }}"

    - name: Print contents of ping_results.log
      shell: cat /tmp/ping_results.log
      register: ping_log_result
      ignore_errors: yes

    - name: Display contents of ping_results.log
      debug:
        msg: "Contents of ping_results.log on {{ inventory_hostname }}: {{ ping_log_result.stdout }}"

    - name: Fetch ping_results.log from remote servers
      fetch:
        src: /tmp/ping_results.log
        dest: /tmp/ping_results_{{ inventory_hostname }}.log
        flat: yes

- name: Combine all ping results into a single file
  hosts: localhost
  tasks:
    - name: Ensure combined results file is empty
      copy:
        content: ""
        dest: /tmp/combined_ping_results.log

    - name: Combine all fetched log files into one
      shell: cat /tmp/ping_results_*.log >> /tmp/combined_ping_results.log

    - name: Display combined ping results
      debug:
        msg: "Combined ping results:\n{{ lookup('file', '/tmp/combined_ping_results.log') }}"
