---
- name: Run script on deployed machines
  hosts: all
  tasks:
    - name: Display the hostname of the current server
      debug:
        msg: "Connected to server: {{ inventory_hostname }}"

    - name: Ensure ping script has execute permission
      file:
        path: /tmp/ping_script.sh
        mode: '0755'
        state: file

    - name: Check if ping script exists
      stat:
        path: /tmp/ping_script.sh
      register: ping_script

    - name: Fail if ping script does not exist
      fail:
        msg: "/tmp/ping_script.sh does not exist on {{ inventory_hostname }}"
      when: not ping_script.stat.exists

    - name: Display the contents of the ping script
      shell: cat /tmp/ping_script.sh
      register: script_content
      ignore_errors: yes

    - name: Print the contents of the ping script
      debug:
        msg: "Contents of /tmp/ping_script.sh on {{ inventory_hostname }}: {{ script_content.stdout }}"

    - name: Run ping script
      shell: /tmp/ping_script.sh
      register: result
      ignore_errors: yes

    - name: Print result of running the script
      debug:
        msg: "Result of running the script on {{ inventory_hostname }}: stdout={{ result.stdout }} stderr={{ result.stderr }}"

    - name: Print contents of ping_results.log
      shell: cat /tmp/ping_results.log
      register: ping_log_result
      ignore_errors: yes

    - name: Display contents of ping_results.log
      debug:
        msg: "Contents of ping_results.log on {{ inventory_hostname }}: {{ ping_log_result.stdout }}"
